Add environment variables needed for Spark2 and Kafka
clusterdock/topology_cdh pull request #24
Opened 2018-05-03 23:21 UTC by kirtiv1

…ations

2018-05-07 22:17 UTC, dimaspivak requested changes

2018-05-07 22:17 UTC, dimaspivak commented on start.py
> +    config_value = 'export SPARK_SUBMIT_YARN_COMMAND=/usr/bin/spark2-submit\nexport SPARK_KAFKA_VERSION=0.10'
How about:
```
environment_variables = {'SPARK_SUBMIT_YARN_COMMAND': '/usr/bin/spark2-submit',                                                   
                         'SPARK_KAFKA_VERSION': '0.10'}                                                                           
configs = {'sdc-env.sh_role_safety_valve': '\n'.join('export {}={}'.format(key, value)                                            
                                                     for key, value in environment_variables.items())}
```

2018-05-07 22:17 UTC, dimaspivak commented on start.py
> +    config_value = 'export SPARK_SUBMIT_YARN_COMMAND=/usr/bin/spark2-submit\nexport SPARK_KAFKA_VERSION=0.10'
Is it really cool like this to hardcode this `SPARK_KAFKA_VERSION` thing or will it potentially bite us at some point?

2018-05-07 23:19 UTC, ujunko commented on start.py
> +    config_value = 'export SPARK_SUBMIT_YARN_COMMAND=/usr/bin/spark2-submit\nexport SPARK_KAFKA_VERSION=0.10'
SPARK_KAFKA_VERSION is a version of Spark x Kafka integration, not just Kafka version. There are only two versions now, Spark2 x Kafka 0.9- and Spark2 x Kafka0.10+. We are testing against later one. Even if user uses Kafka 0.11 or 0.12+, we will keep using "SPARK_KAFKA_VERSION=0.10". I think it makes sense to hardcode this way.

2018-05-08 00:07 UTC, kirtiv1 commented on start.py
> +    config_value = 'export SPARK_SUBMIT_YARN_COMMAND=/usr/bin/spark2-submit\nexport SPARK_KAFKA_VERSION=0.10'
Done.

2018-05-08 18:42 UTC, dimaspivak approved these changes

2018-05-08 21:06 UTC, merged