Add passwords for various CDH versions and reports manager when needed
clusterdock/topology_cdh pull request #56
Opened 2018-09-17 17:16 UTC by kirtiv1

2018-09-20 21:23 UTC, dimaspivak requested changes
Just nits. Yay Navigator support! :)

2018-09-20 21:23 UTC, dimaspivak commented on start.py
> +CDH_VERSIONS_WITH_REPORTS_MANAGER_NEEDED = ['5.10.0', '5.11.1', '5.12.0', '5.13.0']
Can we just check for 5.[10-13] without regard for the last digit?

2018-09-20 21:23 UTC, dimaspivak commented on start.py
> +        command = ("grep com.cloudera.cmf.REPORTSMANAGER.db.password /etc/cloudera-scm-server/db.mgmt.properties | "
Let's replace grep | awk with `Node.get_file` and then grok it with Python code.

2018-09-20 21:23 UTC, dimaspivak commented on start.py
> +    logger.info('Adding Navigator related roles to cluster (%s) ...', DEFAULT_CLUSTER_NAME)
Super nit: just say "Adding Navigator roles to cluster" instead of "Navigator related"

2018-09-20 23:04 UTC, kirtiv1 commented on start.py
> +        command = ("grep com.cloudera.cmf.REPORTSMANAGER.db.password /etc/cloudera-scm-server/db.mgmt.properties | "
Done.

2018-09-20 23:05 UTC, kirtiv1 commented on start.py
> +    logger.info('Adding Navigator related roles to cluster (%s) ...', DEFAULT_CLUSTER_NAME)
Done.

2018-09-21 13:43 UTC, kirtiv1 commented on start.py
> +CDH_VERSIONS_WITH_REPORTS_MANAGER_NEEDED = ['5.10.0', '5.11.1', '5.12.0', '5.13.0']
Done.

2018-09-21 19:20 UTC, dimaspivak approved these changes
Lovely!

2018-09-21 20:09 UTC, merged